### ISSUE TITLE
Owncloud upgrade issue

### ISSUE THREAD

**Issue by babyfooter** [bitnami/bitnami-docker-owncloud#60]
Hi guys,

```
Ubuntu 18.04 LTS
Client: Docker Engine - Community
Version:           19.03.1
Client:
 Debug Mode: false
Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-46-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.836GiB
 Name: ns3274150
 ID: YNOH:YHFN:FCHF:SWNW:CLPS:7GHJ:IHUR:O33I:MFOV:7SSN:ATNF:OJWQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

```console
$ echo $BITNAMI_IMAGE_VERSION
10.2.1-debian-9-r34
$ docker-compose up -d to start container
```

I encoured an issue upgrading my Owncloud instance using `docker-compose`, and following you upgrade guide 

```console
## Get the updated images:
$ docker pull bitnami/owncloud:latest
## Stop your container
$ docker-compose stop owncloud
## Take a snapshot of the application state
$ rsync -a /path/to/owncloud-persistence /path/to/owncloud-persistence.bkp.$(date +%Y%m%d-%H.%M.%S)
## Additionally, snapshot the MariaDB data
## You can use these snapshots to restore the application state should the upgrade fail.
## Remove the currently running container
$ docker-compose rm -v owncloud
## Run the new image
$ docker-compose up -d owncloud`
```

My mistake is that all go well (an upgrade GUI appears after restarting, and completed successfully, bu when logging in, a Owncloud page without any items appears.

<img width="1438" alt="Capture d’écran 2" src="https://user-images.githubusercontent.com/19487037/62920464-22f1bf00-bda6-11e9-9928-645b2dcf22d0.png">

I see in error console an error like:
```
shareconfigmodel.js?v=5aee7a01b4ce4e9fba8691bac46246a0:24 Uncaught ReferenceError: oc_appconfig is not defined
    at shareconfigmodel.js?v=5aee7a01b4ce4e9fba8691bac46246a0:24
    at shareconfigmodel.js?v=5aee7a01b4ce4e9fba8691bac46246a0:99
js.js?v=5aee7a01b4ce4e9fba8691bac46246a0:198 Uncaught TypeError: Cannot read property 'substring' of undefined
    at Object.filePath (js.js?v=5aee7a01b4ce4e9fba8691bac46246a0:198)
    at viewer.js?v=5aee7a01b4ce4e9fba8691bac46246a0:4
owncloud.sagoeparts.com/:1 Failed to load resource: the server responded with a status of 500 ()`
```

Could you help or provide the way to restore my previous container? :( Many thx.

**Comment by juan131** [comment]
Hi @babyfooter 

What version of ownCloud where you running before upgrading? I guess you run the command below after you upgraded your container, didn't you? 

> ```
> $ echo $BITNAMI_IMAGE_VERSION
> 10.2.1-debian-9-r34
> ```

Did you install any theme/plugin?

**Comment by babyfooter** [comment]
I think that was a 9.X version. Yes version is after upgrade.

I may have some plugins installed, should I try to disable it and do you know how?

Thx

**Comment by juan131** [comment]
Hi @babyfooter 

The upgrade process you referred is intended for minor and patch versions. When upgrading from `9.x.x` to `10.x.x`, the process is much more complex.

I tried to reproduce your scenario and I followed the steps below to successfully upgrade from version 9 to version 10:

- Step 1: Use a **docker-compose.yaml** like the one below to deploy ownCloud 9:

```yaml
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_USER=bn_owncloud
      - MARIADB_DATABASE=bitnami_owncloud
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/path/to/mariadb/persisted/directory:/bitnami/mariadb'
  owncloud:
    image: 'bitnami/owncloud:9'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - OWNCLOUD_DATABASE_USER=bn_owncloud
      - OWNCLOUD_DATABASE_NAME=bitnami_owncloud
      - ALLOW_EMPTY_PASSWORD=yes
      - OWNCLOUD_HOST=localhost
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/path/to/owncloud/persisted/directory:/bitnami/owncloud'
    depends_on:
      - mariadb
```

```console
$ mkdir -p /path/to/owncloud/persisted/directory /path/to/mariadb/persisted/directory
$ docker-compose up -d
```

- Step 2: Wait until ownCloud is up (checking the logs) and access the ownCloud server to upload some data (files):

```console
$ docker-compose logs owncloud
...
owncloud_1  | nami    INFO  owncloud successfully initialized
owncloud_1  | INFO  ==> Starting owncloud...
```

- Step 3: Create a snapshot (backup) of the current data and set maintenance mode:

```console
$ rsync -a  /path/to/owncloud/persisted/directory  /path/to/owncloud/persisted/directory.bkp.$(date +%Y%m%d-%H.%M.%S)
$ rsync -a  /path/to/mariadb/persisted/directory  /path/to/mariadb/persisted/directory.bkp.$(date +%Y%m%d-%H.%M.%S)
$ docker-compose exec owncloud bash
# sudo -u daemon /opt/bitnami/php/bin/php /opt/bitnami/owncloud/occ maintenance:mode --on
# exit
```

- Step 4: Stop/Delete ownCloud container:

```console
$ docker-compose stop owncloud
$ docker-compose rm -v owncloud
```

- Step 5: Update the `docker-compose.yaml` and start ownCloud container:

```diff
  owncloud:
-    image: 'bitnami/owncloud:9'
+    image: 'bitnami/owncloud:10'
    environment:
```

```console
$ docker-compose up -d owncloud
```

- Step 6: Wait until ownCloud is up (checking the logs)

```console
$ docker-compose logs owncloud
...
owncloud_1  | nami    INFO  owncloud successfully initialized
owncloud_1  | INFO  ==> Starting owncloud...
```

- Step 7: Run the 'upgrade' command and remove 'maintenance' mode:

```console
$ docker-compose exec owncloud bash
# sudo -u daemon /opt/bitnami/php/bin/php /opt/bitnami/owncloud/occ upgrade
# sudo -u daemon /opt/bitnami/php/bin/php /opt/bitnami/owncloud/occ maintenance:mode --off
# exit
```

- Step 8: Access the ownCloud server again and check the files I uploaded are there
