### ISSUE TITLE
Request to add ImageMagick PHP module

### ISSUE THREAD

**Issue by Crewat** [bitnami/bitnami-docker-owncloud#65]
It is a required PHP module to use [2-Factor Authentication](http://cloud.larspelle.com/index.php/apps/market/#/app/twofactor_totp), described in the solution for this issue: https://github.com/owncloud/twofactor_totp/issues/206.

It is also listed as [a required package in the documentation](https://doc.owncloud.com/server/admin_manual/installation/quick_guides/ubuntu_20_04.html#install-the-required-packages) of ownCloud.

**Comment by migruiz4** [comment]
Hi @Crewat,

ImageMagick is included in the ownCloud docker container but it is not enabled by default.
To enable it, it is necessary to configure `extension = imagick` inside `/opt/bitnami/php/etc/php.ini`

As a temporary solution, you could fix this by using the following command in your `docker-compose.yml`:
```yaml
  owncloud:
    image: 'docker.io/bitnami/owncloud:10-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - OWNCLOUD_DATABASE_HOST=mariadb
      - OWNCLOUD_DATABASE_PORT_NUMBER=3306
      - OWNCLOUD_DATABASE_USER=bn_owncloud
      - OWNCLOUD_DATABASE_NAME=bitnami_owncloud
      - ALLOW_EMPTY_PASSWORD=yes
      - OWNCLOUD_HOST=localhost
    command: bash -c "sed -i 's/;extension = imagick/extension = imagick/' /opt/bitnami/php/etc/php.ini && /opt/bitnami/scripts/owncloud/entrypoint.sh /opt/bitnami/scripts/owncloud/run.sh"
    volumes:
      - 'owncloud_data:/bitnami/owncloud'
    depends_on:
      - mariadb
```

We are adding the fix to have ImageMagick enabled by default and a new image including it should be released soon.

Thank you for reporting this issue.
